ignorefiles = [ "guides/snippets" ]

baseURL = "https://zen-ardinghelli-342594.netlify.com"
languageCode = "en-us"
title = "My New Hugo Site"

theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]
